export const DOC_TYPES = [
  { value: "prd", label: "PRD", emoji: "\u{1F4CB}", description: "Product Requirements Document" },
  { value: "mom", label: "MoM", emoji: "\u{1F4DD}", description: "Minutes of Meeting" },
  { value: "onepager", label: "One-Pager", emoji: "\u{26A1}", description: "Product Brief" },
  { value: "experiment", label: "Experiment Summary", emoji: "\u{1F9EA}", description: "Post-Experiment Review" },
  { value: "experimentDesign", label: "Experiment Design", emoji: "\u{1F52C}", description: "Pre-Experiment Plan" },
  { value: "gtm", label: "GTM Plan", emoji: "\u{1F680}", description: "Go-To-Market Plan" },
  { value: "vision", label: "Vision Doc", emoji: "\u{1F52D}", description: "Strategic Vision & Problem Statement" },
];

export const MILESTONE_FIELDS = [
  "mbObjective",
  "mbScope",
  "mbOutOfScope",
  "mbUserStories",
  "mbAnalytics",
  "mbRollout",
  "mbRisks",
];

export const FORM_SECTIONS = {
  prd: [
    { title: "Background", emoji: "\u{1F4D6}", fields: ["backgroundToday", "backgroundWhyNow"] },
    { title: "Problem & Users", emoji: "\u{1F3AF}", fields: ["problemStatement", "problemUsers"] },
    { title: "Goals", emoji: "\u{2B50}", fields: ["objective", "successMetrics", "milestones"] },
    { title: "Milestone Breakdown", emoji: "\u{1F527}", dynamic: "milestones", fields: [] },
    { title: "Wrap-up", emoji: "\u{1F4E6}", fields: ["openItems"] },
  ],
  mom: [
    { title: "Meeting Info", emoji: "\u{1F4C5}", fields: ["momTitle", "audience", "participants"] },
    { title: "Content", emoji: "\u{270F}\u{FE0F}", fields: ["meetingNotes", "actionItems"] },
  ],
  onepager: [
    { title: "Brief", emoji: "\u{1F4A1}", fields: ["context", "objective", "successMetrics", "expectedOutput", "rolloutStrategy"] },
  ],
  experiment: [
    { title: "Setup", emoji: "\u{2699}\u{FE0F}", fields: ["expContext", "hypothesis"] },
    { title: "Results", emoji: "\u{1F4CA}", fields: ["metricsRaw", "whatWorked", "whatDidnt"] },
    { title: "Decision", emoji: "\u{2705}", fields: ["decision", "nextSteps"] },
  ],
  experimentDesign: [
    { title: "Context", emoji: "\u{1F4D6}", fields: ["edBackground", "edHypothesis", "edSetup"] },
    { title: "Metrics", emoji: "\u{1F4CF}", fields: ["edPrimaryMetrics", "edSecondaryMetrics", "edGuardrails"] },
    { title: "Planning", emoji: "\u{1F5D3}\u{FE0F}", fields: ["edRisks", "edDependencies", "edTimeline", "edOpenQuestions"] },
  ],
  gtm: [
    { title: "Strategy", emoji: "\u{1F9ED}", fields: ["gtmObjective", "gtmSuccessMetrics", "gtmRolloutPrinciples"] },
    { title: "Launch Plan", emoji: "\u{1F680}", fields: ["gtmMilestones", "gtmProductionChecklist", "gtmRolloutStrategy"] },
    { title: "Checklists", emoji: "\u{2611}\u{FE0F}", fields: ["gtmUxChecklist", "gtmOpsChecklist", "gtmClickstream"] },
    { title: "Wrap-up", emoji: "\u{1F4E6}", fields: ["gtmOpenItems", "gtmEvaluation"] },
  ],
  vision: [
    { title: "Context", emoji: "\u{1F30D}", fields: ["visionArea", "visionPeriod", "visionCurrentState"] },
    { title: "Retrospective (optional)", emoji: "\u{1F50D}", fields: ["visionHighlights", "visionLowlights"] },
    { title: "Data & Evidence", emoji: "\u{1F4CA}", fields: ["visionFunnelData", "visionUserResearch"] },
    { title: "Problems & Themes", emoji: "\u{1F6A8}", fields: ["visionProblems", "visionTheme"] },
    { title: "What We're Doing", emoji: "\u{1F3AF}", fields: ["visionInitiatives", "visionReleaseCalendar"] },
    { title: "What We're NOT Doing", emoji: "\u{1F6AB}", fields: ["visionTradeoffs", "visionDeprioritized"] },
    { title: "Risks & Open Items", emoji: "\u{26A0}\u{FE0F}", fields: ["visionRisks", "visionOpenQuestions"] },
  ],
};

export const FORM_FIELDS = Object.fromEntries(
  Object.entries(FORM_SECTIONS).map(([key, sections]) => [
    key,
    sections.flatMap((s) => s.fields),
  ])
);

export const LABEL_MAP = {
  backgroundToday: "Current Situation (today)",
  backgroundWhyNow: "Why Now (context trigger)",
  problemStatement: "Problem Statement",
  problemUsers: "Target Users",
  objective: "Objective",
  successMetrics: "Success Metrics",
  milestones: "Milestones (high-level overview)",
  mbTitle: "Milestone Title",
  mbObjective: "Objective",
  mbScope: "Scope (in-scope)",
  mbOutOfScope: "Out of Scope",
  mbUserStories: "User Stories (raw)",
  mbAnalytics: "Analytics / Clickstream",
  mbRollout: "Rollout Strategy",
  mbRisks: "Risks and Mitigation",
  openItems: "Open Items / Questions",
  momTitle: "MoM Title (topic)",
  audience: "Audience (who needs to read this)",
  participants: "Participants (in the meeting)",
  meetingNotes: "Meeting Notes (raw)",
  actionItems: "Action Items (raw)",
  context: "Context",
  expectedOutput: "Expected Output",
  rolloutStrategy: "Rollout Strategy",
  expContext: "Experiment Context",
  hypothesis: "Hypothesis",
  metricsRaw: "Metrics (raw notes)",
  whatWorked: "What Worked",
  whatDidnt: "What Didn't Work",
  decision: "Decision",
  nextSteps: "Next Steps",
  edBackground: "Background / Context",
  edHypothesis: "Hypothesis (rough)",
  edSetup: "Experiment Setup / Variants",
  edPrimaryMetrics: "Primary Metrics",
  edSecondaryMetrics: "Secondary Metrics",
  edGuardrails: "Guardrail Metrics",
  edRisks: "Risks",
  edDependencies: "Dependencies",
  edTimeline: "Timeline",
  edOpenQuestions: "Open Questions",
  gtmObjective: "Objective",
  gtmSuccessMetrics: "Success Metrics",
  gtmRolloutPrinciples: "Rollout Principles",
  gtmMilestones: "Milestones and Customer Experience",
  gtmProductionChecklist: "Production Checklist",
  gtmRolloutStrategy: "Rollout Strategy",
  gtmOpenItems: "Open Items / Decisions Needed",
  gtmUxChecklist: "User Experience (Functional Checklist)",
  gtmOpsChecklist: "Operational Journey (Functional Checklist)",
  gtmClickstream: "Clickstream Requirements",
  gtmEvaluation: "Evaluation and Measurement",
  visionArea: "Product Area / Scope",
  visionPeriod: "Planning Period (e.g. Q2'25, H2'25)",
  visionCurrentState: "Where we are now (raw observations)",
  visionHighlights: "What went well (highlights)",
  visionLowlights: "What fell short (lowlights)",
  visionFunnelData: "Data / Metrics (paste raw numbers)",
  visionUserResearch: "User research / qualitative signals",
  visionProblems: "Problems we're solving",
  visionTheme: "Key themes or strategic direction",
  visionInitiatives: "Initiatives and what we're building",
  visionReleaseCalendar: "Release calendar / timeline (optional)",
  visionTradeoffs: "Trade-offs (what we chose NOT to do and why)",
  visionDeprioritized: "Deprioritized items",
  visionRisks: "Risks and proposed mitigations",
  visionOpenQuestions: "Open questions / things to figure out",
};

export const PLACEHOLDER_MAP = {
  backgroundToday: "e.g. Today, users land on the home screen but don't find what they need quickly\u2026",
  backgroundWhyNow: "e.g. Conversion dropped 10% last quarter, new infra is ready to support changes\u2026",
  problemStatement: "What's broken? Where does it show up?",
  problemUsers: "e.g. New users in the first 30 days, power users in segment X\u2026",
  objective: "What do we want to achieve?",
  successMetrics: "e.g. Conversion rate, engagement rate, task completion rate\u2026",
  milestones: "e.g. M1: Research and scoping, M2: MVP launch, M3: Full rollout",
  mbTitle: "e.g. MVP Launch",
  mbObjective: "What does this milestone achieve?",
  mbScope: "What's included?",
  mbOutOfScope: "What's explicitly excluded?",
  mbUserStories: "e.g. As a user, I can filter results so that I find relevant items faster\u2026",
  mbAnalytics: "e.g. P0: track page impressions, P1: track filter usage\u2026",
  mbRollout: "e.g. 10% \u2192 30% \u2192 100%, start with one segment\u2026",
  mbRisks: "e.g. Risk: low adoption \u2192 Mitigation: run A/B test first\u2026",
  openItems: "Any unresolved questions or dependencies?",
  momTitle: "e.g. Sprint Planning Kick-off",
  audience: "e.g. Engineering, Product, Design, Data",
  participants: "e.g. Alice, Bob, Charlie, Dana",
  meetingNotes: "Paste your raw notes here\u2026",
  actionItems: "e.g. - Alice: finalize spec by Friday\n- Bob: share design mock by Monday",
  context: "What's happening today and why it matters\u2026",
  expectedOutput: "What artefacts or changes should exist after this work?",
  rolloutStrategy: "How will we phase this out?",
  expContext: "What did we test, on which surface, for which users?",
  hypothesis: "e.g. We believe adding filters will increase conversion by 5%\u2026",
  metricsRaw: "Paste the raw metric results\u2026",
  whatWorked: "Positive signals, patterns, or behaviors\u2026",
  whatDidnt: "Negative or neutral outcomes\u2026",
  decision: "Ship, iterate, roll back, or park?",
  nextSteps: "Concrete follow-ups\u2026",
  edBackground: "What motivates this experiment?",
  edHypothesis: "e.g. We believe <change> will <effect> for <audience>\u2026",
  edSetup: "e.g. Control vs Treatment, 50/50 split, 2-week duration\u2026",
  edPrimaryMetrics: "The metric that decides ship / no-ship\u2026",
  edSecondaryMetrics: "Supporting metrics to watch\u2026",
  edGuardrails: "Metrics that must NOT degrade\u2026",
  edRisks: "What could go wrong?",
  edDependencies: "Eng, design, data, ops blockers\u2026",
  edTimeline: "e.g. Instrumentation: W1, Start: W2, Read-out: W4",
  edOpenQuestions: "Anything still TBD?",
  gtmObjective: "What does this launch aim to achieve?",
  gtmSuccessMetrics: "Primary + guardrail metrics\u2026",
  gtmRolloutPrinciples: "e.g. Start small, validate, then scale\u2026",
  gtmMilestones: "Key milestones from pre-launch to full rollout\u2026",
  gtmProductionChecklist: "What must be true before going live?",
  gtmRolloutStrategy: "e.g. 5% \u2192 20% \u2192 50% \u2192 100%\u2026",
  gtmOpenItems: "Unresolved questions blocking rollout\u2026",
  gtmUxChecklist: "Key user flows and edge cases to validate\u2026",
  gtmOpsChecklist: "Ops processes, SOPs, training needed\u2026",
  gtmClickstream: "Events to instrument before launch\u2026",
  gtmEvaluation: "How and when will we evaluate success?",
  visionArea: "e.g. Discovery Funnel, Checkout Experience, Platform Performance\u2026",
  visionPeriod: "e.g. Q2 2025, H2'25",
  visionCurrentState: "Dump your observations: what's the state of things, what segments matter\u2026",
  visionHighlights: "What went well last period? Key wins, launches, validations\u2026",
  visionLowlights: "What fell short? Adoption gaps, churn signals, delivery delays\u2026",
  visionFunnelData: "Paste raw metrics, funnel data, trend numbers\u2026",
  visionUserResearch: "Research findings, user quotes, qualitative signals\u2026",
  visionProblems: "List problems: can be messy. e.g. 'search irrelevant, onboarding confusing, checkout too slow'\u2026",
  visionTheme: "e.g. Simplify the discovery journey, Complete the review cycle\u2026",
  visionInitiatives: "List what you're building. Group by theme. Mark [NEW], [Spillover], [Proposed]\u2026",
  visionReleaseCalendar: "Paste release calendar. e.g. April: Phase 1, May: Phase 2\u2026",
  visionTradeoffs: "What you're NOT doing and why. e.g. 'Feature X \u2014 not enough resources, plan for Q3'\u2026",
  visionDeprioritized: "Items explicitly parked or deprioritized with rationale\u2026",
  visionRisks: "e.g. 'Churn from segment X \u2014 mitigation: offer discount or extended trial'\u2026",
  visionOpenQuestions: "Data gaps, pending decisions, assumptions to validate\u2026",
};
