export const DOC_TYPES = [
  { value: "prd", label: "PRD – Product Requirements Document" },
  { value: "mom", label: "MoM – Minutes of Meeting" },
  { value: "onepager", label: "One-Pager – Product Brief" },
  { value: "experiment", label: "Experiment Summary – Post-Experiment Review" },
  { value: "experimentDesign", label: "Experiment Design – Pre-Experiment Plan" },
  { value: "gtm", label: "GTM – Go-To-Market Plan" },
];

export const FORM_FIELDS = {
  prd: [
    "backgroundToday",
    "backgroundWhyNow",
    "problemStatement",
    "problemUsers",
    "objective",
    "successMetrics",
    "milestones",
    "mbObjective",
    "mbScope",
    "mbOutOfScope",
    "mbUserStories",
    "mbAnalytics",
    "mbRollout",
    "mbRisks",
    "openItems",
  ],
  mom: [
    "momTitle",
    "audience",
    "participants",
    "meetingNotes",
    "actionItems",
  ],
  onepager: [
    "context",
    "objective",
    "successMetrics",
    "expectedOutput",
    "rolloutStrategy",
  ],
  experiment: [
    "expContext",
    "hypothesis",
    "metricsRaw",
    "whatWorked",
    "whatDidnt",
    "decision",
    "nextSteps",
  ],
  experimentDesign: [
    "edBackground",
    "edHypothesis",
    "edSetup",
    "edPrimaryMetrics",
    "edSecondaryMetrics",
    "edGuardrails",
    "edRisks",
    "edDependencies",
    "edTimeline",
    "edOpenQuestions",
  ],
  gtm: [
    "gtmObjective",
    "gtmSuccessMetrics",
    "gtmRolloutPrinciples",
    "gtmMilestones",
    "gtmProductionChecklist",
    "gtmRolloutStrategy",
    "gtmOpenItems",
    "gtmUxChecklist",
    "gtmOpsChecklist",
    "gtmClickstream",
    "gtmEvaluation",
  ],
};

export const LABEL_MAP = {
  backgroundToday: "Current Situation (today)",
  backgroundWhyNow: "Why Now (context trigger)",
  problemStatement: "Problem Statement",
  problemUsers: "Target Users",
  objective: "Objective",
  successMetrics: "Success Metrics",
  milestones: "Milestones",
  mbObjective: "Milestone Objective",
  mbScope: "Scope (in-scope)",
  mbOutOfScope: "Out of Scope",
  mbUserStories: "User Stories (raw)",
  mbAnalytics: "Analytics / Clickstream Requirements",
  mbRollout: "Rollout Strategy",
  mbRisks: "Risks and Mitigation (raw)",
  openItems: "Open Items / Questions",
  momTitle: "MoM Title (topic)",
  audience: "Audience (who needs to read this)",
  participants: "Participants (in the meeting)",
  meetingNotes: "Meeting Notes (raw)",
  actionItems: "Action Items (raw)",
  context: "Context",
  expectedOutput: "Expected Output",
  rolloutStrategy: "Rollout Strategy",
  expContext: "Experiment Context",
  hypothesis: "Hypothesis",
  metricsRaw: "Metrics (raw notes)",
  whatWorked: "What Worked",
  whatDidnt: "What Didn't Work",
  decision: "Decision",
  nextSteps: "Next Steps",
  edBackground: "Background / Context",
  edHypothesis: "Hypothesis (rough)",
  edSetup: "Experiment Setup / Variants",
  edPrimaryMetrics: "Primary Metrics",
  edSecondaryMetrics: "Secondary Metrics",
  edGuardrails: "Guardrail Metrics",
  edRisks: "Risks",
  edDependencies: "Dependencies",
  edTimeline: "Timeline",
  edOpenQuestions: "Open Questions",
  gtmObjective: "Objective",
  gtmSuccessMetrics: "Success Metrics",
  gtmRolloutPrinciples: "Rollout Principles",
  gtmMilestones: "Milestones and Customer Experience",
  gtmProductionChecklist: "Production Checklist",
  gtmRolloutStrategy: "Rollout Strategy",
  gtmOpenItems: "Open Items / Decisions Needed",
  gtmUxChecklist: "User Experience (Functional Checklist)",
  gtmOpsChecklist: "Operational Journey (Functional Checklist)",
  gtmClickstream: "Clickstream Requirements",
  gtmEvaluation: "Evaluation and Measurement",
};
