export const PLACEHOLDER_MAP = {
  backgroundToday: "e.g. Today, users land on the home screen but don't find what they need quickly\u2026",
  backgroundWhyNow: "e.g. Conversion dropped 10% last quarter, new infra is ready to support changes\u2026",
  problemStatement: "What's broken? Where does it show up?",
  problemUsers: "e.g. New users in the first 30 days, power users in segment X\u2026",
  objective: "What do we want to achieve?",
  successMetrics: "e.g. Conversion rate, engagement rate, task completion rate\u2026",
  milestones: "e.g. M1: Research and scoping, M2: MVP launch, M3: Full rollout",
  mbTitle: "e.g. MVP Launch",
  mbObjective: "What does this milestone achieve?",
  mbScope: "What's included?",
  mbOutOfScope: "What's explicitly excluded?",
  mbUserStories: "e.g. As a user, I can filter results so that I find relevant items faster\u2026",
  mbAnalytics: "e.g. P0: track page impressions, P1: track filter usage\u2026",
  mbRollout: "e.g. 10% \u2192 30% \u2192 100%, start with one segment\u2026",
  mbRisks: "e.g. Risk: low adoption \u2192 Mitigation: run A/B test first\u2026",
  openItems: "Any unresolved questions or dependencies?",
  momTitle: "e.g. Sprint Planning Kick-off",
  audience: "e.g. Engineering, Product, Design, Data",
  participants: "e.g. Alice, Bob, Charlie, Dana",
  meetingNotes: "Paste your raw notes here\u2026",
  actionItems: "e.g. - Alice: finalize spec by Friday\n- Bob: share design mock by Monday",
  context: "What's happening today and why it matters\u2026",
  expectedOutput: "What artefacts or changes should exist after this work?",
  rolloutStrategy: "How will we phase this out?",
  expContext: "What did we test, on which surface, for which users?",
  hypothesis: "e.g. We believe adding filters will increase conversion by 5%\u2026",
  metricsRaw: "Paste the raw metric results\u2026",
  whatWorked: "Positive signals, patterns, or behaviors\u2026",
  whatDidnt: "Negative or neutral outcomes\u2026",
  decision: "Ship, iterate, roll back, or park?",
  nextSteps: "Concrete follow-ups\u2026",
  edBackground: "What motivates this experiment?",
  edHypothesis: "e.g. We believe <change> will <effect> for <audience>\u2026",
  edSetup: "e.g. Control vs Treatment, 50/50 split, 2-week duration\u2026",
  edPrimaryMetrics: "The metric that decides ship / no-ship\u2026",
  edSecondaryMetrics: "Supporting metrics to watch\u2026",
  edGuardrails: "Metrics that must NOT degrade\u2026",
  edRisks: "What could go wrong?",
  edDependencies: "Eng, design, data, ops blockers\u2026",
  edTimeline: "e.g. Instrumentation: W1, Start: W2, Read-out: W4",
  edOpenQuestions: "Anything still TBD?",
  gtmObjective: "What does this launch aim to achieve?",
  gtmSuccessMetrics: "Primary + guardrail metrics\u2026",
  gtmRolloutPrinciples: "e.g. Start small, validate, then scale\u2026",
  gtmMilestones: "Key milestones from pre-launch to full rollout\u2026",
  gtmProductionChecklist: "What must be true before going live?",
  gtmRolloutStrategy: "e.g. 5% \u2192 20% \u2192 50% \u2192 100%\u2026",
  gtmOpenItems: "Unresolved questions blocking rollout\u2026",
  gtmUxChecklist: "Key user flows and edge cases to validate\u2026",
  gtmOpsChecklist: "Ops processes, SOPs, training needed\u2026",
  gtmClickstream: "Events to instrument before launch\u2026",
  gtmEvaluation: "How and when will we evaluate success?",
  visionArea: "e.g. Discovery Funnel, Checkout Experience, Platform Performance\u2026",
  visionPeriod: "e.g. Q2 2025, H2'25",
  visionCurrentState: "Dump your observations: what's the state of things, what segments matter\u2026",
  visionHighlights: "What went well last period? Key wins, launches, validations\u2026",
  visionLowlights: "What fell short? Adoption gaps, churn signals, delivery delays\u2026",
  visionFunnelData: "Paste raw metrics, funnel data, trend numbers\u2026",
  visionUserResearch: "Research findings, user quotes, qualitative signals\u2026",
  visionProblems: "List problems: can be messy. e.g. 'search irrelevant, onboarding confusing, checkout too slow'\u2026",
  visionTheme: "e.g. Simplify the discovery journey, Complete the review cycle\u2026",
  visionInitiatives: "List what you're building. Group by theme. Mark [NEW], [Spillover], [Proposed]\u2026",
  visionReleaseCalendar: "Paste release calendar. e.g. April: Phase 1, May: Phase 2\u2026",
  visionTradeoffs: "What you're NOT doing and why. e.g. 'Feature X \u2014 not enough resources, plan for Q3'\u2026",
  visionDeprioritized: "Items explicitly parked or deprioritized with rationale\u2026",
  visionRisks: "e.g. 'Churn from segment X \u2014 mitigation: offer discount or extended trial'\u2026",
  visionOpenQuestions: "Data gaps, pending decisions, assumptions to validate\u2026",
};
